[package]
name        = "spar-ls"
version     = "0.6.0"
edition     = "2021"
description = "Portable language server (LSP) for the Spar scripting language"
license     = "MIT"
repository  = "https://github.com/oraclevs/spar-ls"
keywords    = ["lsp", "language-server", "spar", "configuration"]
categories  = ["development-tools"]

[[bin]]
name = "spar-ls"
path = "src/main.rs"

[dependencies]
tower-lsp = "0.20"
tokio     = { version = "1", features = ["full"] }
serde_json = "1"
spar      = { path = "../spar", version = "0.6.0" }

[dev-dependencies]
tempfile = "3"
